server:
  port: 1234
  # 开启嵌入式服务器的HTTPS服务
#  ssl:
#    key-store: file:///path/to/mykeys.jks
#    key-store-password: password
#    key-password: password
spring:
  main:
    # 禁用 ascii-art Banner
    show-banner: false
  thymeleaf:
    # 禁用模板缓存
    cache: false
  # 配置数据源
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: org.h2.Driver
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
  file:
    path: /var/logs/BookWarn.log
#    path: /var/logs